{% set name = "pytest-qt" %}
{% set version = "4.2.0" %}
{% set hash = "00a17b586dd530b6d7a9399923a40489ca4a9a309719011175f55dc6b5dc8f41" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-qt/pytest-qt-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  skip: True  # [py<37 or s390x]
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --ignore-installed

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - setuptools_scm
  run:
    - python
    - pytest >=3.0.0

test:
  requires:
    - pip
    - pytest
    - pyqt >=5,<6
  imports:
    - pytestqt
  source_files:
    - setup.cfg
    - tests
  commands:
    - pip check
    - pytest -v tests -k "not (test_region or test_exceptions_dont_leak or test_stop or est_wait_window[waitExposed-True] or test_wait_for_window_shown[True])"  # [win]

about:
  home: https://github.com/pytest-dev/pytest-qt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest support for PyQt and PySide applications
  description: pytest plugin for Qt (PyQt5/PyQt6 and PySide2/PySide6) application testing
  doc_url: https://pytest-qt.readthedocs.io
  dev_url: https://github.com/pytest-dev/pytest-qt

extra:
  recipe-maintainers:
    - nicoddemus
