{% set name = "pytest-qt" %}
{% set version = "4.0.0" %}
{% set hash = "45687ab906f4828eb73d9fca2369326970e4ae0addb7ec0767bf5e968d66b581" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pytest-qt/pytest-qt-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools_scm
  run:
    - python >=3.6
    - pytest

test:
  requires:
    - pyqt 5.*
    - pytest
  imports:
    - pytestqt
  #commands:
  #  - pytest --help
  # skipping tests due to some problem with conda-forge:
  # libGL.so.1: cannot open shared object file: No such file or directory

about:
  home: https://github.com/pytest-dev/pytest-qt
  license: MIT
  license_file: LICENSE
  summary: pytest support for PyQt and PySide applications
  doc_url: http://pytest-qt.readthedocs.io/en/latest/
  dev_url: https://github.com/pytest-dev/pytest-qt

extra:
  recipe-maintainers:
    - nicoddemus
