{% set name = "pytest-qt" %}
{% set version = "4.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-qt/pytest_qt-{{ version }}.tar.gz
  sha256: 51620e01c488f065d2036425cbc1cbcf8a6972295105fd285321eb47e66a319f

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --ignore-installed

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - setuptools_scm
    - setuptools-scm
  run:
    - python
    - pytest
    - pluggy >=1.1
    - typing_extensions

test:
  requires:
    - pip
    - pytest
    - pyqt >=5,<6
  imports:
    - pytestqt
    - pytestqt._version
    - pytestqt.exceptions
    - pytestqt.logging
    - pytestqt.qt_compat
    - pytestqt.qtbot
    - pytestqt.utils
    - pytestqt.wait_signal
  source_files:
    - setup.cfg
    - tests
  commands:
    - pip check
    - pytest -v tests -k "not (test_region or test_exceptions_dont_leak or test_stop or est_wait_window[waitExposed-True] or test_wait_for_window_shown[True])"  # [win]

about:
  home: https://github.com/pytest-dev/pytest-qt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest support for PyQt and PySide applications
  description: pytest plugin for Qt (PyQt5/PyQt6 and PySide2/PySide6) application testing
  doc_url: https://pytest-qt.readthedocs.io
  dev_url: https://github.com/pytest-dev/pytest-qt

extra:
  recipe-maintainers:
    - nicoddemus
