{% set name = "pytest-qt" %}
{% set version = "3.2.0" %}
{% set hash_type = "sha256" %}
{% set hash = "a05a577a6217f062502546f0e8eb10e03fb847cf85416a0d5c4923ba7f09ac05" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pytest-qt/pytest-qt-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python

requirements:
  build:
    - pip
    - python    
    - setuptools
    - setuptools_scm
  run:
    - python
    - pytest

test:
  requires:
    - pyqt 5.*
    - pytest
  imports:
    - pytestqt
  commands:
    - py.test --help

about:
  home: https://github.com/pytest-dev/pytest-qt
  license: MIT
  license_file: LICENSE
  summary: pytest support for PyQt and PySide applications
  doc_url: http://pytest-qt.readthedocs.io/en/latest/
  dev_url: https://github.com/pytest-dev/pytest-qt

extra:
  recipe-maintainers:
    - nicoddemus
