{% set name = "pytest-qt" %}
{% set version = "2.1.2" %}
{% set hash_type = "sha256" %}
{% set hash = "1f029b2aa1654f6b90fb7b2cbebd185cc1de7b792df6fdbb9af948b854a05ff7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pytest-qt/pytest-qt-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - pytest
    - setuptools
    - setuptools_scm
  run:
    - python
    - pytest

test:
  requires:
    # version currently supplied by conda-forge, we might want to test with a newer version
    - pyqt 4.11.*
    - pytest
  imports:
    - pytestqt
  commands:
    - py.test --help

about:
  home: https://github.com/pytest-dev/pytest-qt
  license: MIT
  license_file: LICENSE
  summary: pytest support for PyQt and PySide applications

extra:
  recipe-maintainers:
    - nicoddemus
