travis:
  secure:
    BINSTAR_TOKEN: dA/hV/c6MJBhkECpRjANksSrwftV56QHclJMuMHoqSyP5ELfyaOklo+m20LZl1U2bXo4TSqJEQ3TfjZJ8kWuhqFzdE/qaMOnM6NeIXLeF6a5+3DHnGkoDEpBT6FW4tXmUMPQdDWcu/D+8rEGN8XGxPyl08jiFCPkj1n5VubY7nSqW1TYebftqY4fIEH6k30dh8qFbyNF87xuy4Fyos9+rDLPO3v0F5SIzzKOut41tY27DVnxwvhZVI11vH8XLl/KpPN0kPuqSWcwKAHfRS5I5nrizB7LM5C2negtgL4Ut06Fs5CuK7cuxjXjgcps0rGUmkeEDAl4w/lIZtBJUZWJ8LZd1K5PAkI4rC829QR8l7Gn/NhqppxKyV2vL2l0vqtBCRZAmLOFu77BhUgqMDXDYjqfIwZ4t/IjoB3jN9IO+JjXscK8qOOkCGtoUfLYNWf6joJofhPG1Mss+AifVS+6FY76ZZQIBdxzvfcWpFOW1mAEoDzyw0oIzBCtssU15xFziqNrWv0JbZebY81HoLGImvL87+4jw0kcm2nKxCM2xB6z7dkHtQXPlSWILD58u5mrVEZbArZVcbTS+dRpduE/ymNupc8tj29YxK4/Hy7vjFy2wPiw3y1/uk2qkZHuiJnS5F467TeU3A30btgaLSqeYO5H/V6jYnWh8H1J1LrDSMk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
