travis:
  secure:
    BINSTAR_TOKEN: GI0kRKNhIq39kn9vppNegmfOwUmyHxlHjBO338q8rDzwW0TQ1A/rAxIfOQ6yvMw9pU/4MVyTlUyHZUtZIFFg/J90G5vQpp7WPC79bDM3BMhAfXgsp/wErCTwqwfYHbHMwkfqT/6h9OOiFdhn9E8gGR3OJEyAyCen+5rzOCWWcvFjQRwnlg+hIS3UCH4ckhdZGIzigIpP8xNWwYvxkWlcojlYoV916J2ytSTrhROGta0x25OOEztGDzOPM60T+j+pyL3nTY6IQquszWDU9IdFNMgyEpauJNJjXIAl4zCy4uRJXbdm9yBj9hDrqPvllm1D5iRtQRgQhRnK/6WVvcSC1PsGH6Hz6OpYj0G4tdreAQMUKjqoQSG+cgmhlnvmVqajh+E8oNHyITph+KUI0yn1QVOGnDAJ1COVIKrgsq2j6AatEFt+7hjzk1SSvHB+0TMxP42Kv/IS8+0IUVyYeHsj6zv+P/haFADt5WSzyfrf/x6qcAi8GvNz3doH7LwW4WLqG06pR9+93VNm/mrMx70XLAbq7I+dBqm6XTJUr2MV3sdcRBvbPX6ocBp/pCOtCnbr12TmUwtAcCzXnT1gurq1ZoxpNbhQgF1LEZQJfXhqxCKk8gunTaCda/zDdk52dldtmCeJ7CqtudHmiV3ODORoqxard85+C5wGFU7ol0XwgT0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
