travis:
  secure:
    BINSTAR_TOKEN: Talpy7hLilLuD3la6oUBbcPUG2x0GYb8Jqf0ZZ6lEL3lfKyAX/8vz/sVsKcMt0i6//pU8MrVS3cgviVTzuphu7N+81FGg7v4jeqHeb3Icx++Ii8xQFIuLknVUqMcotQg4f7CsiJ/8nNTduXuMALcYdu9CRLW/d07r5Zk4AyExxA/61yVbyGtNlTLrbPmJfzOAOZoFo05fVKL5d2vwlQfeoQ6Ijqr2kKwCDl7Lu+fNID6Oasqy2GxFLCvVbNdWBkHTYl4CRq4zgKlayovoS+aIFkkSVxEXGafT9yCdarwkqJoRYZooYMSz2ZACPLO6irGAF7NyZRrPK3YN758wqRVG4wfJMF+7vbLFIPp9SzNnyS0Dffu+uZa/N48fk0yQJjia4IpxJzMm2Hy+m7gKQ8N99DWYDeTtQoFSUCAWRzscqMMU2/k46NMu7TecpUvmFinkCj6yL2ckAW1guWxrmXxwyCYRoMozTUKXTUdXgb56iP5IX3nPG21cBJl0XUNTn8zQOca4XyStbNIjKHnrXarEgQh71LbDSog5jxSrOAa2CmUQ0DBSki8H1P+C7fw3kupDGwcZmd/iD50hhR8siskDLmnIZFaThl57qZ3MPlhF6tn4Y8TAjcxa/IsbJXDJuN/fe/AqyBTH5NNt5rlA1Mk9BMaIetqoe62M8XzIzo8dWA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
